### ISSUE TITLE
Update documentation for RapidAPI key setup

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#1]
RAPIDAPI_HOST and RAPIDAPI_KEY which are necessary to make the API calls to our code execution system.

Please update the documentation accodingly on how to create the RAPIDAPI_HOST and RAPIDAPI_KEY

**Comment by Chaitanya1672** [comment]
@DhanushNehru can you tell me how get those RAPIDAPI_HOST  and RAPIDAPI_KEY, I have created account on judge and rapidapi but don't know next steps, do you have some video or something? I can add it in readme but first I'll need to do it.

**Comment by DhanushNehru** [comment]
Hi @Chaitanya1672 , make sure to choose the judge0 free plan , navigate to this url, and start with free plan
https://rapidapi.com/judge0-official/api/judge0-ce/pricing
