### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by rivercory** [DhanushNehru/CustomCodeEditor#106]
![Plugin icon - 1(1)](https://github.com/user-attachments/assets/a0b3cdb4-8ab6-45cf-9e88-979e1016e2d9)
![Plugin icon - 1](https://github.com/user-attachments/assets/96d36f97-4ae9-4972-b4c4-a38fc506e69d)
Why not brand our project with the logo above? (above is my try)

**Comment by DhanushNehru** [comment]
Looks good , go ahead @rivercory
