### ISSUE TITLE
Enhance Code Editor: Implement Real-Time Collaboration Features

### ISSUE THREAD

**Issue by Anikesh02** [DhanushNehru/CustomCodeEditor#109]
## Current Situation
The current repository hosts a basic code editor website where users can write code and view the output.

## Proposed Enhancement
Transform the existing code editor into a comprehensive real-time collaborative development environment.

## Suggested Features
1. Real-time code editing using WebSockets
   - Allow multiple users to edit code simultaneously
   - Implement operational transformation or similar algorithms for conflict resolution

2. Real-time chat functionality
   - Enable developers to communicate within the coding environment
   - Support text, code snippets, and possibly emoji reactions

3. Collaborative whiteboard
   - Provide a shared space for diagramming and visual explanations
   - Include basic drawing tools and the ability to insert text

4. Additional real-time features
   - Cursor presence: Show other users' cursor positions
   - User presence: Display a list of currently active users
   - Version history: Implement a timeline of changes with the ability to revert

I want to work on this issue. Can you please assign this issue to me?

**Comment by DhanushNehru** [comment]
Hi @Anikesh02 seems to be a lot of issues. Can you please raise specific issues for each feature.  That would be great

**Comment by Anikesh02** [comment]
Ok, sure.
