### ISSUE TITLE
Change the title bar icon to something different

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#11]
Currently the title bar icon is based out of react. Change it to something different.

Post the icon here and after confirmation do proceed with the icon change

**Comment by Mohit-3007** [comment]
Hi @DhanushNehru ,

I would like to contribute to your repo
Can you assign this to me!

**Comment by Mohit-3007** [comment]
Hi @DhanushNehru 

check this out

![sample](https://github.com/DhanushNehru/CustomCodeEditor/assets/134084612/a6cb5d4a-72c2-49fe-b3fa-21b26ff7121a)

**Comment by DhanushNehru** [comment]
@Mohit-3007 looks fine, if you can include the same for python as well it will be really cool .
You can check the code for more details

**Comment by DhanushNehru** [comment]
![Screenshot 2024-05-17 at 5 24 55 PM](https://github.com/DhanushNehru/CustomCodeEditor/assets/22955675/d6e1bf76-09e8-42c3-96ff-92eb71f6f686)
This issue was more about changing the icon in this title bar icon instead of react logo @Mohit-3007 
If you want to do the above which you mentioned please raise a new issue @Mohit-3007

**Comment by Mohit-3007** [comment]
> ![Screenshot 2024-05-17 at 5 24 55 PM](https://private-user-images.githubusercontent.com/22955675/331584360-d6e1bf76-09e8-42c3-96ff-92eb71f6f686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NDg0NzksIm5iZiI6MTcxNTk0ODE3OSwicGF0aCI6Ii8yMjk1NTY3NS8zMzE1ODQzNjAtZDZlMWJmNzYtMDllOC00MmMzLTk2ZmYtOTJlYjcxZjZmNjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEyMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmM2VkM2JhNjU5NzAzYWM4ODhmYjU5NDdkNTU1YjRlNThkZjQ5NDY5M2UxYWI5NDIyZDU4ZTBhZmRlOWIyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zyRuxBkg5ZChGYyIA4p_4OWs-xk4fD_esz3RFMCaDcs) This issue was more about changing the icon in this title bar icon instead of react logo @Mohit-3007 If you want to do the above which you mentioned please raise a new issue @Mohit-3007

my bad I misunderstood, will change the title icon

**Comment by Mohit-3007** [comment]
and also python logo and drop down button

![python](https://github.com/DhanushNehru/CustomCodeEditor/assets/134084612/1a0007f2-447b-4ef9-8c6a-73afb5cb001e)
![js](https://github.com/DhanushNehru/CustomCodeEditor/assets/134084612/e1c94b19-7cc0-4853-8482-eca8d2a359a5)

**Comment by DhanushNehru** [comment]
Yes title bar logo looks fine ,  

Can you create a new issue for javascript & python logo @Mohit-3007

**Comment by Mohit-3007** [comment]
@DhanushNehru created new issue for javascript & python logo
