### ISSUE TITLE
External Api Not Working

### ISSUE THREAD

**Issue by PALASH2201** [DhanushNehru/CustomCodeEditor#125]
I came across this repo, thought I could contribute, but the External API is not working. I am getting the submission token but not able to get the submission output as Accepted, either its Runtime Error or Compilation Error
Also I noticed the casing of header names were wrong, so I corrected them according Judge0 CE's requirement

**Comment by DhanushNehru** [comment]
The api limit for code execution is 50 requests per day as it's on free version. If you set up locally you can avail for 50 requests. Can you be specific incase anything missed @PALASH2201

**Comment by PALASH2201** [comment]
The first part that is getting the token for the submission is working but the code getting accepted is not happening. And about the 50 requests, I set up another account to test the api but not working

**Comment by DhanushNehru** [comment]
Please follow all instructions as expected, maybe something might have missed. Many are contributing to the repo and they were able to configure and make things work. Join discord server incase someone might help. @PALASH2201

**Comment by PALASH2201** [comment]
@DhanushNehru I got the error, before making an api call, we have to encode the source code and similarly before showing the output we have to decode it. Should I make the changes ?

**Comment by PALASH2201** [comment]
@DhanushNehru can you assign this task to me?

**Comment by PALASH2201** [comment]
@DhanushNehru Can you add Hackoberfest-accepted  label?
