### ISSUE TITLE
Add Social Icons

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#127]
Checkout this project https://harmonycode.vercel.app/

Similar to this, I want my social icons to be displayed in this code editor app.

Please make sure to display the mock UI and then proceed with PR

**Comment by AE-Hertz** [comment]
hello, @DhanushNehru can you assign me this issue...

**Comment by tusharshah21** [comment]
Hey, @DhanushNehru looks like there are no update for this issue, would be glad if you could reassign it to me. I would love to do it on priority basis

**Comment by DhanushNehru** [comment]
Since it has been more than 5 days @AE-Hertz .

Will merge the PR first of whoever raises it @tusharshah21

**Comment by tusharshah21** [comment]
Hi @DhanushNehru wanted to confirm it, you wanted the icons in the blue border in the image or the pink border in the image?

![Screenshot 2024-10-08 212336](https://github.com/user-attachments/assets/f310ee25-3dd9-494f-bda6-bbc5bb816de9)

**Comment by DhanushNehru** [comment]
Anything which satisfies the UI / UX @tusharshah21

**Comment by tusharshah21** [comment]
https://github.com/user-attachments/assets/d08766b9-ada0-4c21-a92e-5a15ee3e37e0

Hi @DhanushNehru, can you look into it and let me know if it looks good from your point of view too?

**Comment by DhanushNehru** [comment]
Looks good @tusharshah21

**Comment by tusharshah21** [comment]
@DhanushNehru as discussed implemented the icon UI/UX for the footer section
