### ISSUE TITLE
Add documentation in Readme.md to set firebase

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#134]
Checkout this PR

https://github.com/DhanushNehru/CustomCodeEditor/pull/131

Need to add high level documentation in README.md for setting up the project in local ( The firebase configuration for sign up with google )

**Comment by tusharshah21** [comment]
Hi @DhanushNehru this looks like a good work for me to do my first commit at this project, would love it if you could assign it to me!

**Comment by Shreyaww** [comment]
Can you please assign this issue to me as this would be my first contribution in hacktoberfest

**Comment by tusharshah21** [comment]
@DhanushNehru submitted the PR, check it and let me know if is it good to go.

**Comment by tusharshah21** [comment]
submitted a new PR @DhanushNehru as per the changes can you look into it!
