### ISSUE TITLE
Incorporating Sign In with google 

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#14]
Anyone can access the site, it would be great if sign in with google is incorporated

Please mention the steps below before raising a PR on this

**Comment by Anikesh02** [comment]
I want to work on this issue.  Can you please assign it to me ?

**Comment by Anikesh02** [comment]
@DhanushNehru I've raised a PR for this issue. There are certain changes that need to be made. I've provided all the details in the PR description.  Kindly add "hacktoberfest" and "hacktoberfest-accepted" labels in both issue as well as PR.

**Comment by Anikesh02** [comment]
> @DhanushNehru I've raised a PR for this issue. There are certain changes that needs to be done on your side for deployment. I've provided all the details in the PR description. Kindly add "hacktoberfest" and "hacktoberfest-accepted" labels in both issue as well as PR.
