### ISSUE TITLE
Update readme.md for setting up GitHub auth 

### ISSUE THREAD

**Issue by Anikesh02** [DhanushNehru/CustomCodeEditor#142]
Check out this PR:

https://github.com/DhanushNehru/CustomCodeEditor/pull/139

It would be great if someone updated the Readme.md file to set up GitHub auth locally.

I've included all the details in the attached PR. Kindly create high-level documentation for setting up GitHub auth using Firebase.

**Comment by tusharshah21** [comment]
Hey @Anikesh02 @DhanushNehru, I have worked on readme file earlier too I think it would be great if you could assign it to me!

**Comment by Gopal1252** [comment]
Hey, @DhanushNehru @Anikesh02 , could you assign this to me? Would be my first contribution.

**Comment by tusharshah21** [comment]
Any update @DhanushNehru @Anikesh02 ?

**Comment by DhanushNehru** [comment]
Hi @tusharshah21 assigned !

**Comment by tusharshah21** [comment]
@DhanushNehru can you please review it and let me know if there any changes needed
