### ISSUE TITLE
Lack of Shortcut Keys to Run Code in Custom Code Editor

### ISSUE THREAD

**Issue by Incharajayaram** [DhanushNehru/CustomCodeEditor#152]
Description:
- The current implementation of the Custom Code Editor lacks functionality for running code snippets using keyboard shortcuts. This limitation reduces the efficiency of users who prefer using shortcuts for quick code execution.

Steps to Reproduce:
1. Open the Custom Code Editor.
2. Write a code snippet in the editor.
3. Attempt to run the code using common keyboard shortcuts (e.g., Ctrl + Enter, F5).

Expected Behavior:
- Users should be able to execute their code using commonly used shortcut keys, such as Ctrl + Enter or F5, to improve workflow and ease of use.

Actual Behavior:
- There is no shortcut functionality for running code. Users must manually click the "Run" button, which disrupts workflow and slows down the development process.

Reproduces How Often:
- Every time a user writes a code snippet and attempts to run it using shortcut keys.

I would like to work on this issue

**Comment by DhanushNehru** [comment]
Hi @Incharajayaram , of you want to work on the issue, keep it open

I will assign it. After you have completed then we can close it
