### ISSUE TITLE
Mention the number of stars in the repository in the landing page

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#17]
In the landing page need to mention the number of stars in the repo and ask people to support it by starring

Please mention the design here before proceeding with changes

**Comment by Sky-De** [comment]
@DhanushNehru hi, please assign this to me, i would like to implement that, thanks

**Comment by Sky-De** [comment]
@DhanushNehru how do you want it to look like? the logic part is done, just let me know if do you have any specific text or design for it, thanks

**Comment by DhanushNehru** [comment]
@Sky-De something like this on the top right corner. Or you can post your design here post confirmation you can raise PR

https://harmonycode.vercel.app/

**Comment by Sky-De** [comment]
@DhanushNehru here is a screen about the current design, it is same as the link you provided but it also has a loading state and error state for edge cases, I will create PR and share screens there
