### ISSUE TITLE
Customize the landing page with a button to navigate to editor view

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#2]

**Comment by SandeepVashishtha** [comment]
Hi,
I noticed the issue you opened regarding the button style. Could you please provide more details on the type of button you need? For example, do you have any specific color, size, or shape in mind? Any additional information you provide will help us implement the button according to your requirements.

Thank you!

**Comment by DhanushNehru** [comment]
Hi @SandeepVashishtha expecting the button style to be similar to the style found in hackerrank or leetcode code Editor

Or if you want to come up with something unique it's totally fine

**Comment by DhanushNehru** [comment]
Keeping this open for more better enhancements on the Landing Page

**Comment by rivercory** [comment]
@DhanushNehru Since the landing page has been removed, it's probably a good idea to close this issue.
