### ISSUE TITLE
New design for code output

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/CustomCodeEditor#22]
Currently the code output displayed is something like this.

<img width="470" alt="Screenshot 2024-05-18 at 7 31 03 PM" src="https://github.com/DhanushNehru/CustomCodeEditor/assets/22955675/bc4e1b4a-606d-408c-a7db-ad0d322aa128">

Open to ideas for better improvement on the UI/UX

**Comment by doriroz** [comment]
Hi...
I think i would shorten the the width of code editor and instead build a little deshbord on the right side. 
then, the select list langauge code and 'Run Javascript Code' button  will move inside the deshbord
and the console will be seperate with a title and no backgournd wrapped the results . instead, a backgroud color for the console itself .  also, i would move the console error result from the top and gathered with the console code result .

**Comment by DhanushNehru** [comment]
You can go ahead @doriroz

**Comment by syedubaid11** [comment]
Hello ...
Putting the output screen on the right is a much better idea along with UI changes, as said above .
 I would like to work on this issue.
