### ISSUE TITLE
[Bug] Not able to see Java language in dropdown which was added in earlier PR's.

### ISSUE THREAD

**Issue by Chaitanya1672** [DhanushNehru/CustomCodeEditor#65]
The Java language is missing, and the code changes for issue #57, such as moving constants to another file, are missing in the Editor component.
![image](https://github.com/DhanushNehru/CustomCodeEditor/assets/100834122/9a2a5c84-7344-4219-b7c1-79897b6414f7)

**Comment by DhanushNehru** [comment]
Seems I missed it while merging , possible to change it back @Chaitanya1672
