### ISSUE TITLE
Disable Vercel Security Checkpoint

### ISSUE THREAD

**Issue by rivercory** [DhanushNehru/CustomCodeEditor#90]
@DhanushNehru I know that this project is hosted with Vercel and secured with Vercel Security Checkpoint.
Vercel Security Checkpoint is a very good security tool.
But it takes up about 10 seconds of the website's loading time.
This is a very significant loading delay and will cause user abandonment.
What do you think about this?
I recommend disabling Vercel Security Checkpoint.

**Comment by DhanushNehru** [comment]
Hi @rivercory I purposely enabled it. I know it will delay but as security perspective it is needed.
